menu:
  home: Home
  books: books
  movies: movies
  archives: Archives
  tags: Tags
  categories: Categories
  about: About
  

footer:
  powered: "Powered by %s"
  theme: Theme

posts:
  prev: Prev
  next: Next
  prev_post: Prev
  next_post: Next
  toc: Contents
  readmore: Read more..
  visits: Visits
  reward: 'Reward'

books:
  bookReading: 在读
  bookWish: 想读
  bookRead: 读过

movies:
  movieWatching: 在看
  movieWish: 想看
  movieWatched: 看过

copyright:
  author: 'Author'
  link: 'Link'
  license: 'License'

counter:
  archives:
    zero: No Posts
    one: 1 Post
    other: "%d Posts In Total"

  tagcloud:
    zero: No tags
    one: 1 Tag In Total
    other: "%d Tags In Total"

  categories:
    zero: No Categories
    one: 1 Category In Total
    other: "%d Categories In Total"
